GPU_ID: '0'
WORKERS: 1
CUDA: False

TRAIN:
    FLAG: True
    LEARNING_RATE: 0.0001
    BATCH_SIZE: 64
    MAX_EPOCHS: 25
    SNAPSHOT_INTERVAL: 5
    WEIGHT_INIT: "xavier_uniform"
    EALRY_STOPPING: True
    PATIENCE: 5
    CLIP_GRADS: True
    MAX_STEPS: 4
    RECV_OBJECTS: True

DATASET:
    DATA_DIR: '/Users/sebamenabar/Documents/datasets/CLEVR_v1.0/data'
    TRAIN_SCENES_JSON: '/Users/sebamenabar/Documents/TAIA/individual/sm/data/clevr/train/scenes.json'
    VAL_SCENES_JSON: '/Users/sebamenabar/Documents/TAIA/individual/sm/data/clevr/val/scenes.json'
    IMG_DIR: '/Users/sebamenabar/Documents/datasets/CLEVR_v1.0/images'




